### ISSUE TITLE
Some mis coded postcodes

### ISSUE THREAD

**Issue by aubergene** [flashton2003/postcode_to_constituency#1]
I just did spot check on BN21 (should be Eastbourne) and a few of them are miscoded to East Worthing and Shoreham. It looks like perhaps they aren't valid/active postcodes to being with, which might be the cause. Great project, thanks for releasing.

```
BN214ZZ E14000682   East Worthing and Shoreham
```

**Comment by flashton2003** [comment]
Thanks! Ok, I will tidy those BN21 codes up. I'm not sure how to do a more systematic check for invalid postcodes though.
